Feature 167172 report viewer
Flexberry/ember-flexberry-analytics pull request #1
Opened 2019-06-04 12:15 UTC by NSelivanov

Создал компонент для просмотра отчетов Pentaho.

2019-06-24 11:31 UTC, mao29 requested changes

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +    let config = this.get('config');
const вместо let

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +      Ember.$('.report-viewer').find('.next-page-button').removeClass('disabled');
Предлагаю переделать на использование поля компонента в hbs, чтобы класс disabled добавлялся через хелпер

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +    $contentIframe.height(`${$contentIframe.contents().find('body').prop('scrollHeight')}px`);
Предлагаю переделать на свойства компонента

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +    let blob = typeof File === 'function' ?
const вместо let

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +        let runningXHRs = this.get('_runningXHRs') || [];
const вместо let

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +    let runningXHRs = this.get('_runningXHRs') || [];
const

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +      let xhr = runningXHRs.pop();
const

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +      var URL = window.URL || window.webkitURL;
const вместо var здесь и ниже

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +    let _this = this;
const вместо let и var здесь и ниже

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +    let $contentIframe = Ember.$('#content');
const вместо let

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +        let runningXHRs = this.get('_runningXHRs') || [];
const

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +        let parameters = Object.assign(
const

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +        let runningXHRs = this.get('_runningXHRs') || [];
const

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +          let printWindow = window.open('', 'PRINT', 'height=400,width=600');
const

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +        let runningXHRs = this.get('_runningXHRs') || [];
const

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +        let parameters = Object.assign(
const

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +      Ember.$('.report-viewer').find('.prev-page-button').removeClass('disabled');
Предлагаю переделать на свойства компонента

2019-06-24 11:31 UTC, mao29 commented on addon/components/report-viewer.js
> +        let parameters = Object.assign(
const

2019-06-24 11:31 UTC, mao29 commented on tests/dummy/app/controllers/pentaho-sample.js
> +      var currentdate = new Date().toISOString().slice(0, 10);
const

2019-06-24 11:31 UTC, mao29 commented on tests/dummy/app/controllers/pentaho-sample.js
> +          var favorite = [];
const

2019-06-24 11:31 UTC, mao29 commented on tests/dummy/app/controllers/pentaho-sample.js
> +          var res = favorite.join("&parMultiSelect=");
const

2019-06-25 08:54 UTC, DubrovinPavel requested changes

2019-06-25 08:54 UTC, DubrovinPavel commented on addon/components/report-viewer.js
> +      Ember.$('.report-viewer').find('.next-page-button').removeClass('disabled');
Согласен, надо переделать на поля в hbs. Также если где-то останется необходимость обращаться к разметке компонента, нужно делать это через this.$ (тогда выборка будет производиться в рамках текущего компонента), а не Ember.$

2019-06-25 08:54 UTC, DubrovinPavel commented on typings/ember/ember.d.ts
> +interface DOMElement {}
Зачем в аддоне этот файл? Удалить, если он не нужен для работы аддона.

2019-06-25 08:54 UTC, DubrovinPavel commented on addon/components/report-viewer.js
> +  reportParameters: {},
Не нужно делать значениями по умолчанию объекты. Сделать undefined, а в init уже присвоить объекту. Ниже в pentahoReportFormats тоже самое

2019-06-25 08:54 UTC, DubrovinPavel commented on addon/templates/components/report-viewer.hbs
> +  <div id="toolbar">
Учитывая, что на форме может понадобиться разместить несколько таких компонентов, вместо id использовать одноименный class. Далее в шаблоне также заменить id. Соответственно нужно будет еще и стили поправить.

2019-06-25 08:54 UTC, DubrovinPavel commented on addon/components/report-viewer.js
> +      Ember.$('.report-viewer').find('.next-page-button').removeClass('disabled');
Заменить на свойства компонента

2019-06-25 09:33 UTC, mao29 commented on addon/components/report-viewer.js
> +      Ember.$('.report-viewer').find('.next-page-button').removeClass('disabled');
Она останется, потому что там прямо целиком html-контент внутрь iframe проставляется. Я не придумал как это hbs-ом сделать

2019-08-01 09:35 UTC, mao29 requested changes

2019-08-01 09:35 UTC, mao29 commented on addon/components/report-viewer.js
> +        let runningXHRs = this.get('_runningXHRs') || [];
Не поправилось

2019-08-02 11:43 UTC, mao29 approved these changes

2019-09-02 08:24 UTC, bratchikov requested changes

2019-09-02 08:24 UTC, bratchikov commented on LICENSE.md
> +Copyright (c) 2018
New Platform Ltd 2019

2019-09-02 08:24 UTC, bratchikov commented on addon/components/report-viewer.js
> +  layout,
Было бы супер, если бы в этом файле все комментарии были бы написаны по правилам [yuidoc](https://flexberry.github.io/ru/fp_ember-comments-style-yuidoc.html), тогда мы бы могли настроить автогенерацию документации (описание API).

2019-09-04 11:48 UTC, bratchikov approved these changes

2019-09-04 11:48 UTC, merged